package frontend;

import backend.BazaDanych;
import java.awt.Color;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class SlowaFrame extends javax.swing.JFrame {
    
    private int kategoriaId;
    private Map<String, String> slowkaMapa;
    private List<String> polskieSlowa;
    private int biezacyIndeks = 0;
    
    public SlowaFrame(int kategoriaId) {
        this.kategoriaId = kategoriaId;
        setTitle("Fiszki - słówka");
        setSize(550, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();

        // Pobieranie słówek z bazy danych
        slowkaMapa = BazaDanych.pobierzSlowka(kategoriaId);
        polskieSlowa = new ArrayList<>(slowkaMapa.keySet());
        
        if (slowkaMapa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Brak słówek dla wybranej kategorii!", "Informacja", JOptionPane.WARNING_MESSAGE);
            dispose();
            return;
        }
        aktualizujSlowo(); // Wyświetl pierwsze słówko
        setVisible(true);
    }
    
    //wyświetlanie polskich słów
    private void aktualizujSlowo() {
        lblSlowko.setText(polskieSlowa.get(biezacyIndeks));
        lblLicznik.setText("Słówko " + (biezacyIndeks + 1) + "/" + polskieSlowa.size());
    }
    
    
    private String normalizujTekst(String tekst) {
        if (tekst == null) return "";
        tekst = Normalizer.normalize(tekst, Normalizer.Form.NFC); // Normalizacja do jednolitego formatu
        return tekst.replace("\u00A0", " ") // Zamiana twardej spacji (NBSP) na zwykłą
                    .replaceAll("\\s+", " ") // Zamiana wielu spacji na jedną
                    .trim(); // Usunięcie spacji na początku i końcu
}
    
    private void sprawdzOdpowiedz() {
        String odpowiedz = normalizujTekst(txtOdpowiedz.getText());
        String polskieSlowo = polskieSlowa.get(biezacyIndeks);
        String poprawneTlumaczenie = normalizujTekst(slowkaMapa.get(polskieSlowo));
       
        
        if (odpowiedz.equalsIgnoreCase(poprawneTlumaczenie)) { // Sprawdzenie poprawności (bez uwzględniania wielkości liter)
            lblWynik.setText("Poprawnie!");
            lblWynik.setForeground(Color.GREEN); // Zielony kolor dla poprawnej odpowiedzi
        } else {
            lblWynik.setText("Niepoprawnie! Spróbuj ponownie.");
            lblWynik.setForeground(Color.RED); // Czerwony kolor dla błędnej odpowiedzi
        }
    }


    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new SlowaFrame(1)); // Przykład: kategoriaId = 1
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStrzalki = new javax.swing.JPanel();
        btnWstecz = new javax.swing.JButton();
        lblLicznik = new javax.swing.JLabel();
        btnDalej = new javax.swing.JButton();
        pnlTlumaczenie = new javax.swing.JPanel();
        lblWpiszTlumaczenie = new javax.swing.JLabel();
        lblSlowko = new javax.swing.JLabel();
        txtOdpowiedz = new javax.swing.JTextField();
        btnSprawdz = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnUUmlaut = new javax.swing.JButton();
        lblWynik = new javax.swing.JLabel();
        btnPrawidlowa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuStronaGlowna = new javax.swing.JMenu();
        mniStronaGlowna = new javax.swing.JMenuItem();
        mnuPomoc = new javax.swing.JMenu();
        mniJakKorzystac = new javax.swing.JMenuItem();
        mnuWyjscie = new javax.swing.JMenu();
        mniWyjdz = new javax.swing.JMenuItem();

        btnWstecz.setText("<");
        btnWstecz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWsteczActionPerformed(evt);
            }
        });

        lblLicznik.setText("jLabel1");

        btnDalej.setText(">");
        btnDalej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDalejActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStrzalkiLayout = new javax.swing.GroupLayout(pnlStrzalki);
        pnlStrzalki.setLayout(pnlStrzalkiLayout);
        pnlStrzalkiLayout.setHorizontalGroup(
            pnlStrzalkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStrzalkiLayout.createSequentialGroup()
                .addComponent(btnWstecz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(lblLicznik, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(btnDalej, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlStrzalkiLayout.setVerticalGroup(
            pnlStrzalkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStrzalkiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlStrzalkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicznik)
                    .addComponent(btnDalej)
                    .addComponent(btnWstecz))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        lblWpiszTlumaczenie.setText("Wpisz poprawne tłumaczenie słowa:");

        lblSlowko.setText("jLabel1");

        txtOdpowiedz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOdpowiedzActionPerformed(evt);
            }
        });

        btnSprawdz.setText("Sprawdź poprawność");
        btnSprawdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSprawdzActionPerformed(evt);
            }
        });

        btnA.setText("á");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnE.setText("é");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnI.setText("í");
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });

        btnN.setText("ñ");
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });

        btnU.setText("ú");
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        btnUUmlaut.setText("ü");
        btnUUmlaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUUmlautActionPerformed(evt);
            }
        });

        lblWynik.setText("jLabel1");

        btnPrawidlowa.setText("Pokaż prawidłową odpowiedź");

        javax.swing.GroupLayout pnlTlumaczenieLayout = new javax.swing.GroupLayout(pnlTlumaczenie);
        pnlTlumaczenie.setLayout(pnlTlumaczenieLayout);
        pnlTlumaczenieLayout.setHorizontalGroup(
            pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                        .addComponent(lblSlowko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                        .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPrawidlowa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(txtOdpowiedz, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWpiszTlumaczenie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSprawdz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblWynik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUUmlaut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlTlumaczenieLayout.setVerticalGroup(
            pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTlumaczenieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWpiszTlumaczenie)
                .addGap(18, 18, 18)
                .addComponent(lblSlowko)
                .addGap(16, 16, 16)
                .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOdpowiedz, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnN)
                    .addComponent(btnU)
                    .addComponent(btnUUmlaut)
                    .addComponent(btnA)
                    .addComponent(btnE)
                    .addComponent(btnI))
                .addGap(18, 18, 18)
                .addGroup(pnlTlumaczenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSprawdz)
                    .addComponent(lblWynik))
                .addGap(18, 18, 18)
                .addComponent(btnPrawidlowa)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        mnuStronaGlowna.setText("Strona główna");

        mniStronaGlowna.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniStronaGlowna.setText("Przejdź do strony głównej");
        mnuStronaGlowna.add(mniStronaGlowna);

        jMenuBar1.add(mnuStronaGlowna);

        mnuPomoc.setText("Pomoc");

        mniJakKorzystac.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniJakKorzystac.setText("Jak korzystać z fiszek?");
        mnuPomoc.add(mniJakKorzystac);

        jMenuBar1.add(mnuPomoc);

        mnuWyjscie.setText("Wyjście");

        mniWyjdz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniWyjdz.setText("Wyjdź");
        mniWyjdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniWyjdzActionPerformed(evt);
            }
        });
        mnuWyjscie.add(mniWyjdz);

        jMenuBar1.add(mnuWyjscie);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStrzalki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTlumaczenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTlumaczenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(pnlStrzalki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWsteczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWsteczActionPerformed
        if (biezacyIndeks > 0) {
                biezacyIndeks--;
                aktualizujSlowo();
            } else {
                JOptionPane.showMessageDialog(this, "To jest pierwsze słówko!", "Informacja", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnWsteczActionPerformed

    private void txtOdpowiedzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOdpowiedzActionPerformed
        txtOdpowiedz.setText("");
        txtOdpowiedz.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    }//GEN-LAST:event_txtOdpowiedzActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "á");
    }//GEN-LAST:event_btnAActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "ú");
    }//GEN-LAST:event_btnUActionPerformed

    private void mniWyjdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniWyjdzActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniWyjdzActionPerformed

    private void btnDalejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDalejActionPerformed
        if (biezacyIndeks < slowkaMapa.size() - 1) {
            biezacyIndeks++;
            aktualizujSlowo();
        } else {
            JOptionPane.showMessageDialog(this, "To jest ostatnie słówko!", "Informacja", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDalejActionPerformed

    private void btnSprawdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSprawdzActionPerformed
        sprawdzOdpowiedz();
    }//GEN-LAST:event_btnSprawdzActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "é");
    }//GEN-LAST:event_btnEActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "í");
    }//GEN-LAST:event_btnIActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "ñ");
    }//GEN-LAST:event_btnNActionPerformed

    private void btnUUmlautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUUmlautActionPerformed
        txtOdpowiedz.setText(txtOdpowiedz.getText() + "ü");
    }//GEN-LAST:event_btnUUmlautActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnDalej;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnPrawidlowa;
    private javax.swing.JButton btnSprawdz;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnUUmlaut;
    private javax.swing.JButton btnWstecz;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblLicznik;
    private javax.swing.JLabel lblSlowko;
    private javax.swing.JLabel lblWpiszTlumaczenie;
    private javax.swing.JLabel lblWynik;
    private javax.swing.JMenuItem mniJakKorzystac;
    private javax.swing.JMenuItem mniStronaGlowna;
    private javax.swing.JMenuItem mniWyjdz;
    private javax.swing.JMenu mnuPomoc;
    private javax.swing.JMenu mnuStronaGlowna;
    private javax.swing.JMenu mnuWyjscie;
    private javax.swing.JPanel pnlStrzalki;
    private javax.swing.JPanel pnlTlumaczenie;
    private javax.swing.JTextField txtOdpowiedz;
    // End of variables declaration//GEN-END:variables

}
